<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0jtq5Xk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0jtq5Xk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0jtq5Xk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0jtq5Xk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0jtq5Xk\App_KernelDevDebugContainer([
    'container.build_hash' => '0jtq5Xk',
    'container.build_id' => '5972364f',
    'container.build_time' => 1767865633,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0jtq5Xk');
