<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR7dHNlJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR7dHNlJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR7dHNlJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR7dHNlJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR7dHNlJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'R7dHNlJ',
    'container.build_id' => '268778d6',
    'container.build_time' => 1769795653,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR7dHNlJ');
