<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR5exWOD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR5exWOD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR5exWOD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR5exWOD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR5exWOD\App_KernelDevDebugContainer([
    'container.build_hash' => 'R5exWOD',
    'container.build_id' => '2b62fec1',
    'container.build_time' => 1769767980,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR5exWOD');
